# Generated by Django 2.2.5 on 2021-01-24 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiotis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7')], db_column='selection', max_length=100, verbose_name='Seleksi')),
                ('origin', models.TextField(db_column='origin', max_length=1000, verbose_name='Asal')),
                ('type', models.TextField(blank=True, db_column='type', max_length=100, null=True, verbose_name='Tipe')),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Tanggal Laporan')),
                ('umur_jagung_jantan', models.IntegerField(db_column='umur_jagung_jantan', verbose_name='Umur Jagung Jantan (hst)')),
                ('umur_jagung_betina', models.IntegerField(db_column='umur_jagung_betina', verbose_name='Umur Jagung Betina (hst)')),
                ('umur_panen', models.IntegerField(db_column='umur_panen', verbose_name='Umur Panen (hst)')),
            ],
            options={
                'verbose_name': 'Abiotis',
                'verbose_name_plural': 'Abiotis',
                'db_table': 'abiotis',
            },
        ),
    ]
